### ISSUE TITLE
Changing from rain to snow in 5 days forcast

### ISSUE THREAD

**Issue by knutek66** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#11]
Hello and thank you for this fantastic program. 
I live in the north of Norway and here we have snow. 
The thing is that the program dont show snow on 5 days prediction.
I did change the program:
![image](https://user-images.githubusercontent.com/56079640/113400752-980e6f80-93a2-11eb-8a2c-28cd86bc9936.png)
and then it worked. 
Is this the way to solve the issue?

**Comment by fdufnews** [comment]
In my opinion, it has more sens to make the change here
`float SumOfPrecip(float DataArray[], int readings) {
  float sum = 0;
  for (int i = 0; i < readings; i++) sum += DataArray[i];
  return sum;
}
`

**Comment by knutek66** [comment]
It worked fdufnews thank you. 
![image](https://user-images.githubusercontent.com/56079640/113404482-80d28080-93a8-11eb-918f-bbbc5fb5b46c.png)

**Comment by G6EJD** [comment]
I changed that and in v3.5 not yet completed.

**Comment by EdjOne** [comment]
> It worked fdufnews thank you.
> ![image](https://user-images.githubusercontent.com/56079640/113404482-80d28080-93a8-11eb-918f-bbbc5fb5b46c.png)

where you bought frame?

**Comment by G6EJD** [comment]
I think he 3D printed it.

**Comment by knutek66** [comment]
Found it here: https://www.thingiverse.com/thing:4749075

**Comment by EdjOne** [comment]
> https://www.thingiverse.com/thing:4749075

Thanks
