### ISSUE TITLE
Wind arrow direction 

### ISSUE THREAD

**Issue by EdjOne** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#12]
Hi G6EJD

How to turn over wind arrow? For me, it's logically - north wind coming from north, so arrow should be from north to compass center.

**Comment by G6EJD** [comment]
It matches the convention on wind direction used by all metrological services!

**Comment by EdjOne** [comment]
Ok, but hot to turn over just a arrow? I'm studied at marine academy, wind coming to compass and current from compass. So, for me it's little bit confusion (with that wind arrow).

**Comment by EdjOne** [comment]
![image](https://user-images.githubusercontent.com/54913815/113510929-d99b4800-9565-11eb-89e3-46dc10ed673a.png)
even OWM shows "correct" direction of arrow

**Comment by EdjOne** [comment]
I have found solution)))
![image](https://user-images.githubusercontent.com/54913815/113511588-29c7d980-9569-11eb-88a8-469f913ddb38.png)
