### ISSUE TITLE
Last forecast day disappeared 

### ISSUE THREAD

**Issue by EdjOne** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#13]
Hi, i have 3.5 version, this morning was noticed that last forecast day is disappeared. Yesterday and today pictures. No any change of code in between.

![IMG_20210404_180003](https://user-images.githubusercontent.com/54913815/113540924-ce89fb80-95e9-11eb-80e0-6678b38cfaa8.jpg)
![IMG_20210405_083058](https://user-images.githubusercontent.com/54913815/113540927-d053bf00-95e9-11eb-9afa-ba1f05bd9f0d.jpg)

**Comment by EdjOne** [comment]
After next update (interval 30mins), is OK

![IMG_20210405_092337](https://user-images.githubusercontent.com/54913815/113545401-c08ca880-95f2-11eb-9e4d-172cdd0b3a4b.jpg)

**Comment by G6EJD** [comment]
There’s no code issue, it means that OWM have not yet published the last forecast period, it will have cleared by now and be published. It happens every day.
