### ISSUE TITLE
Perceived temperature addition

### ISSUE THREAD

**Issue by Kabron287** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#3]
I guess displaying the perceived temperature would be the icing on the cake.
This is how I did:
`float calcTe(float Ta, int RH, float V) {
	#define ee 2.718281828
	float E;
	E = (RH / 100.0)*6.105*pow(ee,  (17.27*Ta / (237.7 + Ta)));
	return (Ta + 0.348*E-0.7*V-4.25);
}`
In DisplayTemperatureSection:
` float Te = calcTe(WxConditions[0].Temperature, WxConditions[0].Humidity, WxConditions[0].Windspeed);
drawString(x - 30, y, String(WxConditions[0].Temperature, 1) + "° (" + String(Te, 1)+"°) " + String(WxConditions[0].Humidity, 0) + "%", LEFT)`

Calculation details here:
https://planetcalc.ru/2089/

**Comment by G6EJD** [comment]
I’ll have a look, can you use the built-in exp() rather that using power

**Comment by G6EJD** [comment]
I'm adding this in version 2.7 the value form OWM in the onecall API
