### ISSUE TITLE
'Latitude' was not defined for this scope - 2.71

### ISSUE THREAD

**Issue by lbonherbe** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#6]
Hello!

Trying to update my working 2.2 to this 2.71 version, when I compile I get the following error :

C:\Users\lbonh\OneDrive\Bureau\LilyGo-EPD-4-7-OWM-Weather-Display-main\OWM_EPD47_epaper_v2.71\OWM_EPD47_epaper_v2.71.ino: In function 'bool obtainWeatherData(WiFiClient&, const String&)':

OWM_EPD47_epaper_v2.71:270:55: error: 'Latitude' was not declared in this scope

   String uri = "/data/2.5/" + RequestType + "?lat=" + Latitude + "&lon=" + Longitude + "&appid=" + apikey + "&mode=json&units=" + units + "&lang=" + Language;

                                                       ^

OWM_EPD47_epaper_v2.71:270:76: error: 'Longitude' was not declared in this scope

   String uri = "/data/2.5/" + RequestType + "?lat=" + Latitude + "&lon=" + Longitude + "&appid=" + apikey + "&mode=json&units=" + units + "&lang=" + Language;

**Comment by lbonherbe** [comment]
My bad I had a previous credentials file that did not have latitude and longitude in...

**Comment by G6EJD** [comment]
It was in the readme 😀
