### ISSUE TITLE
What a strange formula?

### ISSUE THREAD

**Issue by Kabron287** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#7]
```percentage = 2836.9625 * pow(voltage, 4) - 43987.4889 * pow(voltage, 3) + 255233.8134 * pow(voltage, 2) - 656689.7123 * voltage + 632041.7303;```
Is there a reference for this calculation?
It shows crazy values.
![Batt](https://user-images.githubusercontent.com/2493191/110429882-9b248180-80bc-11eb-93b9-59cffc67580a.jpg)

**Comment by G6EJD** [comment]
yes, it a match to  atypical Li-Ion battery charge/discharge curve, so that 0-100% corresponds to a battery voltage of 4.2 down to 3.5, but here your x-range is to wide. Change it to 3.5 to 4.2 and you will see 0-100% on the y-axis.

**Comment by Kabron287** [comment]
But the device works fine down to 3V, while the meter begins to grow to 100% and then to negative values.

**Comment by G6EJD** [comment]
The polynomial is designed for the Lolin D32 with on-board regulator and a 0.6v dropout, on that board if works perfectly and gives a near linear indication of battery capacity from 200% down to 0. Also discharging Li-ion batteries down below 3.2v leads to cell damage. Yes the ESP32 can run at lower voltages but I designed the algorithm to work within the normal range for a lithium cell.
What problems are you seeing with the algorithm?

**Comment by G6EJD** [comment]
Have you ever generated a polynomial, I use the tabular method. Why not have a go at producing one?
