### ISSUE TITLE
Unable to compile with Arduino

### ISSUE THREAD

**Issue by andysilvester** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#8]
Hi, not sure if this is the right place but here goes:
I have the LilyGo EPD_47 board and have spent many hours trying to get it working with the weather-display app. The compile always seems to fail due to issues with the Arduino_JSON library. I'm not expert in Arduino at all but have tried-and-re-tried de-and re-installing libraries and even completely uninstalled and reinstalled arduino IDE in case there were other/previous files corrupting my setup.

There's probably a simple fix but having repeatedly tried with all the instructions available, am here as a last resort for guidance / help. Luckily, the board isn't expensive and I can give-up and forget it, but having seen Pawel Spychalski's excellent YT presentation (and of course followed his guidance without success), I'd really like to get my weather-display working!

How should I proceed, please?

Thanks, Andy
UK

**Comment by fdufnews** [comment]
Did you install the ArduinoJson library from Benoit Blanchon?
Copy and paste the message from the compiler.

**Comment by G6EJD** [comment]
Ive compiled the code recently and there are no issues with latest libraries, so this is puzzling. Yes as suggested please copy the standard compiler error messages (not verbose)

**Comment by andysilvester** [comment]
> Did you install the ArduinoJson library from Benoit Blanchon? There is another one with a very similar name.
> Copy and paste the message from the compiler.

YES! That fixed it - many thanks! The Library I had installed before was Arduino_JSON. I substituted this one and it compiled successfully. 

Thanks again,

Andy

**Comment by andysilvester** [comment]
Following the success of compiling, I am now trying to get the upload onto the board - it appears to show the transfer working but the board itself doesn't respond, either with USB power or with battery connected. Here's the text (in red) from the IDE:

Sketch uses 1022102 bytes (77%) of program storage space. Maximum is 1310720 bytes.
Global variables use 45500 bytes (13%) of dynamic memory, leaving 282180 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.0-dev
Serial port COM3
Connecting........_
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 40:f5:20:55:30:d0
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 16MB
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 10922.6 kbit/s)...
Hash of data verified.
Flash params set to 0x024f
Compressed 18656 bytes to 12053...
Writing at 0x00001000... (100 %)
Wrote 18656 bytes (12053 compressed) at 0x00001000 in 0.2 seconds (effective 877.9 kbit/s)...
Hash of data verified.
Compressed 1022336 bytes to 614713...
Writing at 0x00010000... (2 %)
Writing at 0x00014000... (5 %)
Writing at 0x00018000... (7 %)
Writing at 0x0001c000... (10 %)
Writing at 0x00020000... (13 %)
Writing at 0x00024000... (15 %)
Writing at 0x00028000... (18 %)
Writing at 0x0002c000... (21 %)
Writing at 0x00030000... (23 %)
Writing at 0x00034000... (26 %)
Writing at 0x00038000... (28 %)
Writing at 0x0003c000... (31 %)
Writing at 0x00040000... (34 %)
Writing at 0x00044000... (36 %)
Writing at 0x00048000... (39 %)
Writing at 0x0004c000... (42 %)
Writing at 0x00050000... (44 %)
Writing at 0x00054000... (47 %)
Writing at 0x00058000... (50 %)
Writing at 0x0005c000... (52 %)
Writing at 0x00060000... (55 %)
Writing at 0x00064000... (57 %)
Writing at 0x00068000... (60 %)
Writing at 0x0006c000... (63 %)
Writing at 0x00070000... (65 %)
Writing at 0x00074000... (68 %)
Writing at 0x00078000... (71 %)
Writing at 0x0007c000... (73 %)
Writing at 0x00080000... (76 %)
Writing at 0x00084000... (78 %)
Writing at 0x00088000... (81 %)
Writing at 0x0008c000... (84 %)
Writing at 0x00090000... (86 %)
Writing at 0x00094000... (89 %)
Writing at 0x00098000... (92 %)
Writing at 0x0009c000... (94 %)
Writing at 0x000a0000... (97 %)
Writing at 0x000a4000... (100 %)
Wrote 1022336 bytes (614713 compressed) at 0x00010000 in 10.3 seconds (effective 791.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 4915.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

I've tried the following:

1. Swapping to the short USB-C cable which came with the board
2. pressing the board's 'reset' button with power connected, and while connecting power
3. Making sure the 18650 cell is connected correctly and is fully charged

Should the board 'weather display' work without issue after uploading or is there another step? After all this compiling problem, I hope I don't have a bad board!

Cheers, Andy

**Comment by G6EJD** [comment]
What is the serial port/monitor saying? Copy please?

**Comment by G6EJD** [comment]
In the tab credentials you updated your WiFi details?
Added your OWM API key?
Set the Lat/Lon?
Set the hemisphere?
Time server?

**Comment by andysilvester** [comment]
> What is the serial port/monitor saying? Copy please?

The monitor window shows nothing until just after the upload - then this:

⸮S⸮⸮!⸮⸮⸮/⸮|⸮⸮⸮/⸮V⸮⸮⸮⸮⸮⸮⸮⸮m幥})⸮⸮⸮⸮

Andy

> In the tab credentials you updated your WiFi details?
> Added your OWM API key?
> Set the Lat/Lon?
> Set the hemisphere?
> Time server?

I set my WiFi credentials, hemisphere and time server, but I didn't know about the OWM API key (thanks). I cut-and-pasted a chosen key from the Open Weather site (API section) into the owm_credentials.h file, saved it and re-compiled/uploaded. Still no display!

Do I need the battery connected for the upload or will USB power be ok?

Andy

**Comment by G6EJD** [comment]
USB power is all you need.
Did you enable PSRAM? In the boards option
Have you set the serial monitor to 115200 baud?
If working correctly the serial monitor will show all the weather data being received.
Copy the serial monitor to here click in the window then CTRL-A then CTRL-C then paste here

**Comment by andysilvester** [comment]
> USB power is all you need. <OK Thanks>
> Did you enable PSRAM? In the boards option <Yes>
> Have you set the serial monitor to 115200 baud? <I have now, thanks!>
> If working correctly the serial monitor will show all the weather data being received.
> Copy the serial monitor to here click in the window then CTRL-A then CTRL-C then paste here:

C:\Users\Andy\Documents\Arduino\LilyGo-EPD-4-7-OWM-Weather-Display-main\OWM_EPD47_epaper_v2.72\OWM_EPD47_epaper_v2.72.ino
Starting...

Connecting to: Pedro13
WiFi connected at: 192.168.0.38
Fri Mar 26 2021   16:10:13
connection failed, error: connection failed, error: connection failed, error: connection failed, error: Received all weather data...
Fri Mar 26 2021   16:10:22
Awake for : 9.987-secs
Entering 3008 (secs) of sleep time
Starting deep-sleep period...

**Comment by andysilvester** [comment]
Can you have a look at my credentials file please? I'm not sure I have the OWM API correct:

const bool DebugDisplayUpdate = false;

// Change to your WiFi credentials
const char* ssid     = "----added----";
const char* password = "----added----";

// Use your own API key by signing up for a free developer account at https://openweathermap.org/
String apikey       = "pro.openweathermap.org/data/2.5/forecast/hourly?q={city name}&appid={api key}";                      // See: https://openweathermap.org/
const char server[] = "api.openweathermap.org";
//http://api.openweathermap.org/data/2.5/forecast?q=Melksham,UK&APPID=your_OWM_API_key&mode=json&units=metric&cnt=40
//http://api.openweathermap.org/data/2.5/weather?q=Melksham,UK&APPID=your_OWM_API_key&mode=json&units=metric&cnt=1

//Set your location according to OWM locations
String City             = "Oxford";                          // Your home city See: http://bulk.openweathermap.org/sample/
String Latitude         = "51.75";                         // Latitude of your location in decimal degrees
String Longitude        = "-1.28";                         // Longitude of your location in decimal degrees
String Language         = "EN";                            // NOTE: Only the weather description is translated by OWM
                                                           // Examples: Arabic (AR) Czech (CZ) English (EN) Greek (EL) Persian(Farsi) (FA) Galician (GL) Hungarian (HU) Japanese (JA)
                                                           // Korean (KR) Latvian (LA) Lithuanian (LT) Macedonian (MK) Slovak (SK) Slovenian (SL) Vietnamese (VI)
String Hemisphere       = "north";                         // or "south"  
String Units            = "M";                             // Use 'M' for Metric or I for Imperial 
const char* Timezone    = "GMT0BST,M3.5.0/1,M10.5.0";      // Choose your time zone from: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv 
                                                           // See below for examples
const char* ntpServer   = "0.uk.pool.ntp.org";             // Or, choose a time server close to you, but in most cases it's best to use pool.ntp.org to find an NTP server
                                                           // then the NTP system decides e.g. 0.pool.ntp.org, 1.pool.ntp.org as the NTP syem tries to find  the closest available servers
                                                           // EU "0.europe.pool.ntp.org"
                                                           // US "0.north-america.pool.ntp.org"
                                                           // See: https://www.ntppool.org/en/                                                           
int   gmtOffset_sec     = 0;    // UK normal time is GMT, so GMT Offset is 0, for US (-5Hrs) is typically -18000, AU is typically (+8hrs) 28800
int  daylightOffset_sec = 3600; // In the UK DST is +1hr or 3600-secs, other countries may use 2hrs 7200 or 30-mins 1800 or 5.5hrs 19800 Ahead of GMT use + offset behind - offset

// Example time zones
//const char* Timezone = "MET-1METDST,M3.5.0/01,M10.5.0/02"; // Most of Europe
//const char* Timezone = "CET-1CEST,M3.5.0,M10.5.0/3";       // Central Europe
//const char* Timezone = "EST-2METDST,M3.5.0/01,M10.5.0/02"; // Most of Europe
//const char* Timezone = "EST5EDT,M3.2.0,M11.1.0";           // EST USA  
//const char* Timezone = "CST6CDT,M3.2.0,M11.1.0";           // CST USA
//const char* Timezone = "MST7MDT,M4.1.0,M10.5.0";           // MST USA
//const char* Timezone = "NZST-12NZDT,M9.5.0,M4.1.0/3";      // Auckland
//const char* Timezone = "EET-2EEST,M3.5.5/0,M10.5.5/0";     // Asia
//const char* Timezone = "ACST-9:30ACDT,M10.1.0,M4.1.0/3":   // Australia

**Comment by G6EJD** [comment]
Test your API key by using one of the examples in the credentials file, replace the text api key with your key then click on the line it will make a request be care to use your key board cursor to move to the correct position then delete the example text then paste in your key then use your mouse to activate the link there will be a lot of text come back if correct or an error message if not.

**Comment by G6EJD** [comment]
Your serial monitor output will give a much better I dictation if things are working

**Comment by G6EJD** [comment]
Board Serial Monitor then press the reset switch that’s the top left most button

**Comment by andysilvester** [comment]
> Test your API key by using one of the examples in the credentials file, replace the text api key with your key then click on the line it will make a request be care to use your key board cursor to move to the correct position then delete the example text then paste in your key then use your mouse to activate the link there will be a lot of text come back if correct or an error message if not.

Ok I'm getting there - I think!

I've registered at the Open Weather site for my API key and have it now by return email. I have to wait until it is activated and will try again in a few hours. Thanks for the assistance so far - with your help I'm sure I can get it done.

Andy

**Comment by G6EJD** [comment]
Yes getting close now, you should be able to go to your account and copy the key from there too

**Comment by andysilvester** [comment]
> Yes getting close now, you should be able to go to your account and copy the key from there too

Inserting my API key into the example line I get the return of a lot of data so the key works!

It's still failing to communicate properly - I'm sure I have problems with the following lines in the credentials file:

// Use your own API key by signing up for a free developer account at https://openweathermap.org/
String apikey       = "https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude={part}&appid=1b10f16168f6e767c7ddcfd63bdbdb0a";                      // See: https://openweathermap.org/
const char server[] = "api.openweathermap.org";
//http://api.openweathermap.org/data/2.5/forecast?q=Melksham,UK&APPID=1b10f16168f6e767c7ddcfd63bdbdb0a&mode=json&units=metric&cnt=40
//http://api.openweathermap.org/data/2.5/weather?q=Melksham,UK&APPID=your_OWM_API_key&mode=json&units=metric&cnt=1

//Set your location according to OWM locations
String City             = "Oxford";                          // Your home city See: http://bulk.openweathermap.org/sample/
String Latitude         = "51.75";                         // Latitude of your location in decimal degrees
String Longitude        = "-1.28";                         // Longitude of your location in decimal degrees
String Language         = "EN";                            // NOTE: Only the weather description is translated by OWM
                                                           // Examples: Arabic (AR) Czech (CZ) English (EN) Greek (EL) Persian(Farsi) (FA) Galician (GL) Hungarian (HU) Japanese (JA)
                                                           // Korean (KR) Latvian (LA) Lithuanian (LT) Macedonian (MK) Slovak (SK) Slovenian (SL) Vietnamese (VI)
String Hemisphere       = "north";                         // or "south"  
String Units            = "M";                             // Use 'M' for Metric or I for Imperial 
const char* Timezone    = "GMT0BST,M3.5.0/1,M10.5.0";      // Choose your time zone from: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv 
                                                           // See below for examples
const char* ntpServer   = "0.uk.pool.ntp.org";   

Do I have to exactly match the String variables as-per the API line, i.e. for 'lat' I have 'Latitude' already defined in the file. I'm trying to understand what is supposed to be contained in the imported API line from the OWM site and how that relates to the 'String' variables shown further down.

Thanks, Andy

**Comment by fdufnews** [comment]
The AP
I key is only this part
"1b10f16168f6e767c7ddcfd63bdbdb0a"

**Comment by fdufnews** [comment]
Once your program is running, you'd better edit your messages and erase your API key otherwise other people may use it.

**Comment by G6EJD** [comment]
It would be better if you get the original credentials file back, there is only 3 lines that need to be modified WiFi said password and API number leave all the rest as mine, then test it, then go back and change to your Lat Lon all elements are commented out / leave as is

**Comment by andysilvester** [comment]
> It would be better if you get the original credentials file back, there are only 3 lines to be modified WiFi ssid & password and API number leave all the rest as mine, then test it, then go back and change to your Lat Lon all elements are commented out / leave as is

Now working - very many thanks for all your patience and help - I'm very pleased with the result so thanks for your efforts. Apologies for the roundabout way of trying to fix it - it was a good learning experience!

Cheers, Andy

**Comment by G6EJD** [comment]
Good to hear
